name: mediaboxAdvanced
author: iaian7
category: Interface
tags: [image, video, audio, media, gallery, modal, overlay]
#docs: http://iaian7.com/webcode/mediaboxAdvanced
#demo: http://iaian7.com/webcode/mediaboxAdvanced
#current: 1.4.6